project:
  type: book
  output-dir: docs

book:
  title: "Running with GLMMs in R"
  author: "George Ellis"
  date: "2025-05-19"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - chapter1.qmd
#    - references.qmd

bibliography: references.bib
csl: chicago-notes.csl
citation-location: document  # 👈 Important for per-chapter bibliographies

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

